CREATE TABLE stage_plots (
    id VARCHAR(255) PRIMARY KEY,
    band_id VARCHAR(255) NOT NULL UNIQUE,
    plot_data TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
